---
x-init-ollama: &init-ollama
  command:
    - -c
    - |
      sleep 3;
      OLLAMA_HOST=${CONTAINER_NAME:-ollama}${NAME_SUFFIX:-}:11434;
      ollama pull $${OLLAMA_BASE_MODEL:-smollm2};
      ollama pull $${OLLAMA_EMBEDDING_MODEL:-nomic-embed-text};
  container_name: ollama-init${NAME_SUFFIX:-}
  entrypoint: /bin/sh
  image: ollama/ollama:latest
  volumes:
    - ./ollama_data:/root/.ollama

x-ollama: &service-ollama
  container_name: ${CONTAINER_NAME:-ollama}${NAME_SUFFIX:-}
  environment:
    - OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION:-1}
    - OLLAMA_KV_CACHE_TYPE=${OLLAMA_KV_CACHE_TYPE:-q8_0}
    - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-2}
  image: ollama/ollama:latest
  restart: unless-stopped
  volumes:
    - ./ollama_data:/root/.ollama

services:
  ollama-cpu:
    <<: *service-ollama
    profiles:
      - cpu
  ollama-gpu:
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              count: 1
              driver: nvidia
    image: ollama/ollama:latest
    profiles:
      - gpu-nvidia
  ollama-gpu-amd:
    <<: *service-ollama
    devices:
      - /dev/kfd
      - /dev/dri
    image: ollama/ollama:rocm
    profiles:
      - gpu-amd
  ollama-init-pull-cpu:
    <<: *init-ollama
    depends_on:
      - ollama-cpu
    profiles:
      - cpu
  ollama-init-pull-gpu:
    <<: *init-ollama
    depends_on:
      - ollama-gpu
    image: ollama/ollama:latest
    profiles:
      - gpu-nvidia
  ollama-init-pull-gpu-amd:
    <<: *init-ollama
    depends_on:
      - ollama-gpu-amd
    image: ollama/ollama:rocm
    profiles:
      - gpu-amd
