---
services:
  ollama-cpu:
    depends_on:
      - tailscaled
    network_mode: service:tailscaled
  ollama-gpu:
    depends_on:
      - tailscaled
    network_mode: service:tailscaled
  ollama-gpu-amd:
    depends_on:
      - tailscaled
    network_mode: service:tailscaled
  tailscaled:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: tailscaled
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_EXTRA_ARGS=--auth-key file:/run/secrets/tailscale_authkey
      - TS_HOSTNAME=ollama-server
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    image: tailscale/tailscale:stable
    restart: unless-stopped
    secrets:
      - tailscale_authkey
    volumes:
      - tailscale_state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun

secrets:
  tailscale_authkey:
    file: secrets/tailscale_authkey.txt

volumes:
  tailscale_state: