---
name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint -c .yamllint.yml .

  validate-cpu:
    runs-on: ubuntu-latest
    needs: yamllint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate CPU configuration
        uses: ./.github/actions/validate-compose
        with:
          profile: cpu
          output-file: cpu-config.yml
          env: |
            OLLAMA_PORT=127.0.0.1:11434
            OLLAMA_VERSION=latest
            OLLAMA_NETWORK_NAME=ollama-net
            OLLAMA_NETWORK_EXTERNAL=false

  validate-nvidia-gpu:
    runs-on: ubuntu-latest
    needs: yamllint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate GPU NVIDIA configuration
        uses: ./.github/actions/validate-compose
        with:
          profile: nvidia-gpu
          output-file: nvidia-gpu-config.yml
          env: |
            OLLAMA_PORT=127.0.0.1:11434
            OLLAMA_VERSION=latest
            OLLAMA_NETWORK_NAME=ollama-net
            OLLAMA_NETWORK_EXTERNAL=false

  validate-amd-gpu:
    runs-on: ubuntu-latest
    needs: yamllint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate GPU AMD configuration
        uses: ./.github/actions/validate-compose
        with:
          profile: amd-gpu
          output-file: amd-gpu-config.yml
          env: |
            OLLAMA_PORT=127.0.0.1:11434
            OLLAMA_VERSION=latest
            OLLAMA_NETWORK_NAME=ollama-net
            OLLAMA_NETWORK_EXTERNAL=false

  validate-tailscale-cpu:
    runs-on: ubuntu-latest
    needs: yamllint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Tailscale CPU configuration
        uses: ./.github/actions/validate-compose
        with:
          profile: tailscale-cpu
          output-file: tailscale-cpu-config.yml
          env: |
            OLLAMA_PORT=127.0.0.1:11434
            OLLAMA_VERSION=latest
            TAILSCALE_VERSION=stable
            OLLAMA_NETWORK_NAME=ollama-net
            OLLAMA_NETWORK_EXTERNAL=false
            OLLAMA_ENABLE_TRAEFIK=false

  validate-tailscale-nvidia-gpu:
    runs-on: ubuntu-latest
    needs: yamllint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Tailscale GPU NVIDIA configuration
        uses: ./.github/actions/validate-compose
        with:
          profile: tailscale-nvidia-gpu
          output-file: tailscale-nvidia-gpu-config.yml
          env: |
            OLLAMA_PORT=127.0.0.1:11434
            OLLAMA_VERSION=latest
            TAILSCALE_VERSION=stable
            OLLAMA_NETWORK_NAME=ollama-net
            OLLAMA_NETWORK_EXTERNAL=false
            OLLAMA_ENABLE_TRAEFIK=false

  validate-tailscale-amd-gpu:
    runs-on: ubuntu-latest
    needs: yamllint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Tailscale GPU AMD configuration
        uses: ./.github/actions/validate-compose
        with:
          profile: tailscale-amd-gpu
          output-file: tailscale-amd-gpu-config.yml
          env: |
            OLLAMA_PORT=127.0.0.1:11434
            OLLAMA_VERSION=latest
            TAILSCALE_VERSION=stable
            OLLAMA_NETWORK_NAME=ollama-net
            OLLAMA_NETWORK_EXTERNAL=false
            OLLAMA_ENABLE_TRAEFIK=false
