---
name: Validate Docker Compose

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create ollama-network
        run: |
          docker network create --driver bridge ollama-net || true

      - name: Create dummy .env file
        run: |
          touch .env

      - name: Create dummy tsauthkey
        run: |
          echo "dummy-key" > tsauthkey

      - name: Upload setup artifacts
        uses: actions/upload-artifact@v4
        with:
          name: setup-artifacts
          path: |
            .env
            tsauthkey
          retention-days: 7

  validate-cpu:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Move .env to working directory
        run: |
          mv setup-artifacts/.env .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate CPU configuration
        uses: ./.github/actions/validate-compose
        with:
          profile: cpu
          output-file: cpu-config.yml
          env: |
            OLLAMA_PORT=127.0.0.1:11434
            OLLAMA_VERSION=latest
            OLLAMA_NETWORK_NAME=ollama-net
            OLLAMA_NETWORK_EXTERNAL=false

      - name: Upload CPU configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpu-config
          path: cpu-config.yml
          retention-days: 7

  validate-gpu-nvidia:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Move .env to working directory
        run: |
          mv setup-artifacts/.env .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate GPU NVIDIA configuration
        uses: ./.github/actions/validate-compose
        with:
          profile: gpu-nvidia
          output-file: gpu-nvidia-config.yml
          env: |
            OLLAMA_PORT=127.0.0.1:11434
            OLLAMA_VERSION=latest
            OLLAMA_NETWORK_NAME=ollama-net
            OLLAMA_NETWORK_EXTERNAL=false

      - name: Upload GPU NVIDIA configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpu-nvidia-config
          path: gpu-nvidia-config.yml
          retention-days: 7

  validate-gpu-amd:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Move .env to working directory
        run: |
          mv setup-artifacts/.env .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate GPU AMD configuration
        uses: ./.github/actions/validate-compose
        with:
          profile: gpu-amd
          output-file: gpu-amd-config.yml
          env: |
            OLLAMA_PORT=127.0.0.1:11434
            OLLAMA_VERSION=latest
            OLLAMA_NETWORK_NAME=ollama-net
            OLLAMA_NETWORK_EXTERNAL=false

      - name: Upload GPU AMD configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpu-amd-config
          path: gpu-amd-config.yml
          retention-days: 7

  validate-tailscale-cpu:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Move .env to working directory
        run: |
          mv setup-artifacts/.env .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Tailscale CPU configuration
        uses: ./.github/actions/validate-compose
        with:
          profile: tailscale-cpu
          output-file: tailscale-cpu-config.yml
          env: |
            OLLAMA_PORT=127.0.0.1:11434
            OLLAMA_VERSION=latest
            TAILSCALE_VERSION=stable
            OLLAMA_NETWORK_NAME=ollama-net
            OLLAMA_NETWORK_EXTERNAL=false
            OLLAMA_ENABLE_TRAEFIK=false

      - name: Upload Tailscale CPU configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-cpu-config
          path: tailscale-cpu-config.yml
          retention-days: 7

  validate-tailscale-gpu-nvidia:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Move .env to working directory
        run: |
          mv setup-artifacts/.env .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Tailscale GPU NVIDIA configuration
        uses: ./.github/actions/validate-compose
        with:
          profile: tailscale-gpu-nvidia
          output-file: tailscale-gpu-nvidia-config.yml
          env: |
            OLLAMA_PORT=127.0.0.1:11434
            OLLAMA_VERSION=latest
            TAILSCALE_VERSION=stable
            OLLAMA_NETWORK_NAME=ollama-net
            OLLAMA_NETWORK_EXTERNAL=false
            OLLAMA_ENABLE_TRAEFIK=false

      - name: Upload Tailscale GPU NVIDIA configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-gpu-nvidia-config
          path: tailscale-gpu-nvidia-config.yml
          retention-days: 7

  validate-tailscale-gpu-amd:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Move .env to working directory
        run: |
          mv setup-artifacts/.env .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Tailscale GPU AMD configuration
        uses: ./.github/actions/validate-compose
        with:
          profile: tailscale-gpu-amd
          output-file: tailscale-gpu-amd-config.yml
          env: |
            OLLAMA_PORT=127.0.0.1:11434
            OLLAMA_VERSION=latest
            TAILSCALE_VERSION=stable
            OLLAMA_NETWORK_NAME=ollama-net
            OLLAMA_NETWORK_EXTERNAL=false
            OLLAMA_ENABLE_TRAEFIK=false

      - name: Upload Tailscale GPU AMD configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-gpu-amd-config
          path: tailscale-gpu-amd-config.yml
          retention-days: 7