---
name: Validate Docker Compose

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Create ollama-network
        run: |
          docker network create --driver bridge ollama-net || true

      - name: Create dummy .env file
        run: |
          touch .env

      - name: Create dummy tsauthkey
        run: |
          echo "dummy-key" > tsauthkey

      - name: Create override file for tailscale profile
        run: |
          echo "services:" > tailscale-override.yml
          echo "  tailscale:" >> tailscale-override.yml
          echo "    profiles: ['tailscale']" >> tailscale-override.yml
          echo "  ollama-cpu-tailscale:" >> tailscale-override.yml
          echo "    profiles: ['tailscale']" >> tailscale-override.yml

      - name: Upload setup artifacts
        uses: actions/upload-artifact@v4
        with:
          name: setup-artifacts
          path: |
            .env
            tsauthkey
            tailscale-override.yml
          retention-days: 7

  validate-cpu:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo mv docker-compose /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Validate and store CPU configuration
        run: |
          docker-compose -f docker-compose.yml --profile cpu config > cpu-config.yml
        env:
          OLLAMA_PORT: 127.0.0.1:11434
          OLLAMA_VERSION: latest
          OLLAMA_NETWORK_NAME: ollama-net
          OLLAMA_NETWORK_EXTERNAL: false

      - name: Upload CPU configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpu-config
          path: cpu-config.yml
          retention-days: 7

  validate-gpu-nvidia:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo mv docker-compose /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Validate and store GPU NVIDIA configuration
        run: |
          docker-compose -f docker-compose.yml --profile gpu-nvidia config > gpu-nvidia-config.yml
        env:
          OLLAMA_PORT: 127.0.0.1:11434
          OLLAMA_VERSION: latest
          OLLAMA_NETWORK_NAME: ollama-net
          OLLAMA_NETWORK_EXTERNAL: false

      - name: Upload GPU NVIDIA configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpu-nvidia-config
          path: gpu-nvidia-config.yml
          retention-days: 7

  validate-gpu-amd:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo mv docker-compose /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Validate and store GPU AMD configuration
        run: |
          docker-compose -f docker-compose.yml --profile gpu-amd config > gpu-amd-config.yml
        env:
          OLLAMA_PORT: 127.0.0.1:11434
          OLLAMA_VERSION: latest
          OLLAMA_NETWORK_NAME: ollama-net
          OLLAMA_NETWORK_EXTERNAL: false

      - name: Upload GPU AMD configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpu-amd-config
          path: gpu-amd-config.yml
          retention-days: 7

  validate-tailscale:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo mv docker-compose /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Validate and store Tailscale configuration
        run: |
          docker-compose -f docker-compose.yml -f tailscale-override.yml --profile tailscale config > tailscale-config.yml
        env:
          OLLAMA_PORT: 127.0.0.1:11434
          OLLAMA_VERSION: latest
          TAILSCALE_VERSION: stable
          OLLAMA_NETWORK_NAME: ollama-net
          OLLAMA_NETWORK_EXTERNAL: false
          OLLAMA_ENABLE_TRAEFIK: false

      - name: Upload Tailscale configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-config
          path: tailscale-config.yml
          retention-days: 7

  validate-tailscale-cpu:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo mv docker-compose /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Validate and store Tailscale CPU configuration
        run: |
          docker-compose -f docker-compose.yml --profile tailscale-cpu config > tailscale-cpu-config.yml
        env:
          OLLAMA_PORT: 127.0.0.1:11434
          OLLAMA_VERSION: latest
          TAILSCALE_VERSION: stable
          OLLAMA_NETWORK_NAME: ollama-net
          OLLAMA_NETWORK_EXTERNAL: false
          OLLAMA_ENABLE_TRAEFIK: false

      - name: Upload Tailscale CPU configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-cpu-config
          path: tailscale-cpu-config.yml
          retention-days: 7

  validate-tailscale-gpu-nvidia:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo mv docker-compose /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Validate and store Tailscale GPU NVIDIA configuration
        run: |
          docker-compose -f docker-compose.yml --profile tailscale-gpu-nvidia config > tailscale-gpu-nvidia-config.yml
        env:
          OLLAMA_PORT: 127.0.0.1:11434
          OLLAMA_VERSION: latest
          TAILSCALE_VERSION: stable
          OLLAMA_NETWORK_NAME: ollama-net
          OLLAMA_NETWORK_EXTERNAL: false
          OLLAMA_ENABLE_TRAEFIK: false

      - name: Upload Tailscale GPU NVIDIA configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-gpu-nvidia-config
          path: tailscale-gpu-nvidia-config.yml
          retention-days: 7

  validate-tailscale-gpu-amd:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo mv docker-compose /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Validate and store Tailscale GPU AMD configuration
        run: |
          docker-compose -f docker-compose.yml --profile tailscale-gpu-amd config > tailscale-gpu-amd-config.yml
        env:
          OLLAMA_PORT: 127.0.0.1:11434
          OLLAMA_VERSION: latest
          TAILSCALE_VERSION: stable
          OLLAMA_NETWORK_NAME: ollama-net
          OLLAMA_NETWORK_EXTERNAL: false
          OLLAMA_ENABLE_TRAEFIK: false

      - name: Upload Tailscale GPU AMD configuration artifact
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-gpu-amd-config
          path: tailscale-gpu-amd-config.yml
          retention-days: 7
